name: PR Preview

on: pull_request

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Cache packages
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-packages-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Restore packages
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-packages-${{ hashFiles('**/yarn.lock') }}

      - name: Cache dist
        uses: actions/cache@v2
        with:
          path: dist
          key: dist-${{ github.sha }}

      - name: build
        run: yarn build
    needs: setup

  deploy:
    name: Deploy Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Restore dist
        uses: actions/cache@v2
        with:
          path: dist
          key: dist-${{ github.sha }}

      - name: Upload Surge Service
        id: deploy
        run: |
          export DEPLOY_DOMAIN=https://preview-${{ github.event.number }}-zarm-design.surge.sh
          npx surge --project ./dist --domain $DEPLOY_DOMAIN --token ${{ secrets.SURGE_TOKEN }}

      - name: Update Status Comment
        uses: actions-cool/maintain-one-comment@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            [https://preview-${{ github.event.number }}-zarm-design.surge.sh](https://preview-${{ github.event.number }}-zarm-design.surge.sh)
            <!-- AUTO_PREVIEW_HOOK -->
          body-include: '<!-- AUTO_PREVIEW_HOOK -->'
          number: ${{ github.event.number }}
    needs: build
